add README.md
Firesieht/MIPT-Python pull request #1
Opened 2024-10-20 21:11 UTC by Firesieht

2024-10-21 06:23 UTC, dKosarevsky requested changes
нужно добавить:

- ФИО
- номер группы
- версии python, которые будет поддерживать приложение
- развёрнутое описание архитектуры

2024-10-29 20:56 UTC, dKosarevsky commented
где необходимые правки?

2024-10-30 14:04 UTC, Firesieht commented
Добавил правки

2024-11-03 21:49 UTC, dKosarevsky approved these changes
Приступай к разработке

2024-11-03 21:49 UTC, merged