dev 1.0
Firesieht/MIPT-Python pull request #2
Opened 2024-11-06 10:22 UTC by Firesieht

2024-11-18 00:04 UTC, dKosarevsky requested changes
необходимо:

- поправить код по комментам к ревью
- добавить инструкцию по запуску приложения
- комментарии к методам оформить в виде docstr
- избыточные комментарии - удалить
- написать тесты
- добавить test coverage
- запуск тестов в GA
- отображать плашку coverage в ридми

2024-11-18 00:04 UTC, dKosarevsky commented on culture/migrations/__pycache__/0001_initial.cpython-311.pyc
кэш в репе не должен быть, этот файл и все остальные - убрать

2024-11-18 00:04 UTC, dKosarevsky commented on culture/models.py
> +    # def clean(self):
зачем этот тут?

2024-11-18 00:04 UTC, dKosarevsky commented on culture/models.py
> +    def __str__(self):
- rtype hint

2024-11-18 00:04 UTC, dKosarevsky commented on culture/models.py
> +    def __str__(self):
- rtype hint

2024-11-18 00:04 UTC, dKosarevsky commented on culture/models.py
> +    def __str__(self):
- rtype hint

2024-11-18 00:04 UTC, dKosarevsky commented on culture/models.py
> +    def __str__(self):
- rtype hint

2024-11-18 00:04 UTC, dKosarevsky commented on culture/models.py
> +def author_mapping(sender, instance, created, *args, **kwargs):
- typehints

2024-11-18 00:04 UTC, dKosarevsky commented on culture/models.py
> +def get_exhibits(sender, instance, created, *args, **kwargs):
- typehints

2024-11-18 00:04 UTC, dKosarevsky commented on culture/models.py
> +def get_exhibits_(sender, instance, created, *args, **kwargs):
- typehints

2024-11-18 00:04 UTC, dKosarevsky commented on culture/models.py
> +def get_exhibits_(sender, instance, created, *args, **kwargs):
- typehints

2024-11-18 00:04 UTC, dKosarevsky commented on culture/models.py
> +def fuck3(sender, instance, created, *args, **kwargs):
- typehints
- naming весёлый, но что ты хотел этим сказать?

2024-11-18 00:04 UTC, dKosarevsky commented on culture/tests.py
> +# Create your tests here.
где?)

2024-11-18 00:04 UTC, dKosarevsky commented on culture/views.py
> +# Create your views here.
вьюхи не используешь?

2024-11-18 00:04 UTC, dKosarevsky commented on db.sqlite3
pg осилишь?

2024-11-18 00:04 UTC, dKosarevsky commented on entertainment/admin.py
> +    pass
зачем?

2024-11-18 00:04 UTC, dKosarevsky commented on entertainment/migrations/__pycache__/0001_initial.cpython-311.pyc
опять кэш...

2024-11-18 00:04 UTC, dKosarevsky commented on entertainment/tests.py
> +# Create your tests here.
где?

2024-11-18 00:04 UTC, dKosarevsky commented on nto/settings.py
> +SECRET_KEY = 'django-insecure-$_)j0dc6hptmuxo2d6te!h=2m%%jcxrj)8v+wtdo12$1pk@ddu'
даже автокоммент Жанги как бы намекает, убери в енвы гитхаба

2024-11-18 00:04 UTC, dKosarevsky commented on nto/urls.py
> +URL configuration for nto project.
мусор следует убрать

2024-11-18 00:04 UTC, dKosarevsky commented on nto/wsgi.py
> +WSGI config for nto project.
аналогично, автогенерируемые комменты не нужны

2024-11-18 00:04 UTC, dKosarevsky commented on session1/__pycache__/models.cpython-312.pyc
кэш...

2024-11-18 00:04 UTC, dKosarevsky commented on session1/models.py
> +    def suply(self):
- rtype hint

2024-11-18 00:04 UTC, dKosarevsky commented on session1/models.py
> +    def __str__(self):
- rtype hint

2024-11-18 00:04 UTC, dKosarevsky commented on session1/models.py
> +    def __str__(self): return self.name
- rtype hint

2024-11-18 00:04 UTC, dKosarevsky commented on session1/models.py
> +class Prostranstvo(models.Model):
нейминг - огонь

2024-11-18 00:04 UTC, dKosarevsky commented on session1/models.py
> +class Prostranstvo(models.Model):
нет

2024-11-18 00:04 UTC, dKosarevsky commented on session1/models.py
> +    def __str__(self):
- rtype hint

2024-11-18 00:04 UTC, dKosarevsky commented on session1/models.py
> +    def upload_excel(value):
- typehints

2024-11-18 00:04 UTC, dKosarevsky commented on session1/models.py
> +    def __str__(self):
- rtype hint

2024-11-18 00:04 UTC, dKosarevsky commented on session1/models.py
> +    def __str__(self):
- rtype hint

2024-11-18 00:04 UTC, dKosarevsky commented on session1/models.py
> +            print(our_locs, allowed_locs)
зачем?

2024-11-18 00:04 UTC, dKosarevsky commented on session1/models.py
> +            # if not len(our_locs) == len(allowed_locs):
мусор?

2024-11-18 00:04 UTC, dKosarevsky commented on session1/models.py
> +    def __str__(self):
- rtype hint

2024-11-18 00:04 UTC, dKosarevsky commented on session1/models.py
> +    def upload_excel(value):
- typehints

2024-11-18 00:04 UTC, dKosarevsky commented on session1/models.py
> +        return self.name
- rtype hint

2024-11-18 00:04 UTC, dKosarevsky commented on session1/models.py
> +    def __str__(self):
- rtype hint

2024-11-18 00:04 UTC, dKosarevsky commented on session1/models.py
> +    def __str__(self):
- rtype hint

2024-11-18 00:04 UTC, dKosarevsky commented on session1/models.py
> +    def __str__(self):
- rtype hint

2024-11-18 00:04 UTC, dKosarevsky commented on session1/models.py
> +    def __str__(self):
- rtype hint

2024-11-18 00:04 UTC, dKosarevsky commented on session1/models.py
> +    def __str__(self):
- rtype hint

2024-11-18 00:04 UTC, dKosarevsky commented on session1/models.py
> +    def upload_excel(value):
- typehints

2024-12-08 10:24 UTC, Firesieht commented on culture/models.py
> +    # def clean(self):
Это нужно чтобы имена на русском красиво подставлялись в админку на русском языке, а если про модель зачем она нужна, то такая бизнес логика проекта, чтобы создать выставку, нужно чтобы выпустился приказ об этом. Просто такая абстракция

2024-12-08 10:25 UTC, Firesieht commented on culture/models.py
> +    def __str__(self):
def __str__(self) нужен для нормального отображение инстантсов моделей в админке, для этого нужен этот метон, и его нельзя поменять на хинт

2024-12-08 10:25 UTC, Firesieht commented on culture/views.py
> +# Create your views here.
Не использую, потому что за фронтенд отвечает джанго админка и все в ней находится

2024-12-08 10:28 UTC, Firesieht commented on db.sqlite3
В джанго это просто поменять настройку, в settings указать хост пароль и логин, отстальное не поменяется. А вот вам запустить и иметь наполненную базу данных будет значительно сложнее, потому я считаю что postgres тут нет смысла добавлять, потому что мне это просто поменять конфиг, а проверку это значительно усложняет. (если вопрос в настройке постгреса на серваке, могу показать что я это умею, если это как то на что то влияет)

2024-12-08 11:14 UTC, Firesieht commented on culture/models.py
> +def fuck3(sender, instance, created, *args, **kwargs):
Просто не придумал название функции, подумал что потом исправлю, но забыл исправить

2024-12-08 11:14 UTC, Firesieht commented on culture/tests.py
> +# Create your tests here.
напишу

2024-12-08 11:23 UTC, Firesieht commented on entertainment/admin.py
> +    pass
Для того чтобы были инлайн поля при создании и при просмотре модели в админке
Это удобнее. Это некий костыль, БД реляционная и у меня же не может в поле хранится список, потому приходится создавать еще модель и foreign key

2024-12-08 11:23 UTC, Firesieht commented on nto/settings.py
> +SECRET_KEY = 'django-insecure-$_)j0dc6hptmuxo2d6te!h=2m%%jcxrj)8v+wtdo12$1pk@ddu'
уберу

2024-12-08 12:06 UTC, Firesieht commented on session1/models.py
> +            print(our_locs, allowed_locs)
Это проверка при сохранении, clean (это не очищение модели как можно подумать, а метод вызываемый при сохранении модели)

А так это просто проверка что мы устанавливаем цены на платное событие и на правильное пространство

А принт - когда тестил, тогда и добавил

2024-12-08 12:06 UTC, Firesieht commented on session1/models.py
> +            # if not len(our_locs) == len(allowed_locs):
законменнченое постарался везде убрать

2024-12-08 22:38 UTC, Firesieht commented
1. Изменил код как написали
2. Добавил инструкцию по запуску STARTUP.md
3. Добавил комментарии к каждому методу класса и самим классам
4. Добавил тесты
5. Удалил закомменченные куски кода
6. Пытался добавить coverage, у меня проходит тесты, а когда пишешь просто run он падает где то внутри джанги по поводу баз данных и какизх то моделей, кароче я не смог разобраться нормально

2024-12-15 10:43 UTC, dKosarevsky approved these changes

2024-12-15 10:43 UTC, merged